# Generated by Django 4.1.2 on 2023-05-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=10)),
                ('EmailId', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
